// <auto-generated />
namespace BLogicLicense.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RunSeedMethod : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RunSeedMethod));
        
        string IMigrationMetadata.Id
        {
            get { return "201708180516237_Run Seed Method"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
